version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/codify
      CODE_RUNNER_VOLUME_NAME: ${CODE_RUNNER_VOLUME_NAME}
    volumes:
      - code-temp:/code-temp
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  frontend:
    build:
      context: ../CODIFY-Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - app
    environment:
      - BACKEND_URL=http://app:3000  # proxy target inside Docker network
    volumes:
      - ../CODIFY-Frontend:/app      # hot reload
      - /app/node_modules           
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codify
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  sandbox:
    build: ./code-runner
    image: code-runner-c
    volumes:
      - code-temp:/code-temp
    command: ["sleep", "infinity"]

volumes:
  code-temp:
    name: ${CODE_RUNNER_VOLUME_NAME}
  postgres-data:
    name: ${DB_VOLUME_NAME}